port: 3030
host: 0.0.0.0
author: Erick Tucto
github: "https://github.com/ericktucto"
twitter: "https://twitter.com/erick_tucto"
youtube: "https://www.youtube.com/@ericktucto"
permalink: /:year-:month-:day-:title
collections:
    projects:
        output: true
        permalink: /projects/:slug
