author: Erick Tucto
email: "erick@ericktucto.com"
linkedin: "https://www.linkedin.com/in/ericktucto"
tiktok: "https://www.tiktok.com/@erickenelcodigo"
github: "https://github.com/ericktucto"
youtube: "https://www.youtube.com/@ericktucto"
permalink: /:year-:month-:day-:title
url: "https://ericktucto.com"
baseurl: ""
repository: ericktucto/ericktucto.github.io
collections:
    projects:
        output: true
        permalink: /projects/:slug
markdown: kramdown
plugins:
    - jekyll-feed
    - jekyll-sitemap
exclude:
    - _scripts
    - vendor/
    - bundle/
    - .git/
    - node_modules/
    - Gemfile
    - Gemfile.lock
    - package.json
    - package-lock.json

keep_files:
  - assets/js
  - assets/css
