author: Erick Tucto
github: "https://github.com/ericktucto"
twitter: "https://twitter.com/erick_tucto"
youtube: "https://www.youtube.com/@ericktucto"
permalink: /:year-:month-:day-:title
markdown: kramdown
# exclude:
#   - .git/
#   - node_modules/
#   - Gemfile
#   - Gemfile.lock
#   - package.json
#   - package-lock.json
